[project]
name = "browser-use-experiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "browser-use[memory]>=0.2.5",
    "openai>=1.84.0",
    "pydantic>=2.10.6",
    "python-dotenv>=1.1.0",
    "rich>=14.0.0",
]
