# Bugninja Configuration
# This file contains global project configuration (LLM, logging, etc.)
# Task-specific settings (browser, agent, etc.) are in individual task_*.toml files
# Sensitive data (API keys, passwords) should be stored in .env file

[project]
name = "test_init"

[llm]
provider = "azure_openai"
model = "gpt-4.1"
temperature = 0.0

[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
enable_rich_logging = true
logging_enabled = false

[development]
debug_mode = false

[paths]
tasks_dir = "./tasks"
traversals_dir = "./traversals"
screenshots_dir = "./screenshots"

[events]
publishers = ["null"]

[llm.azure_openai]
api_version = "2024-02-15-preview"

[llm.openai]
base_url = "https://api.openai.com/v1"

[llm.anthropic]
base_url = "https://api.anthropic.com"

[llm.google_gemini]
base_url = "https://generativelanguage.googleapis.com"

[llm.deepseek]
base_url = "https://api.deepseek.com"

[llm.ollama]
base_url = "http://localhost:11434"